modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/JackFred2/ChestTracker/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/JackFred2/ChestTracker"
logoFile="assets/chesttracker/icon.png"
authors="JackFred; unofficial NeoForge port"
description='''Client-side item storage and searching for Minecraft. This is an unofficial NeoForge 1.21.1 port of Chest Tracker.'''

[[mixins]]
config="chesttracker.mixins.json"

[[mixins]]
config="jackfredlib-gps.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[3.5.0,)"
ordering="AFTER"
side="CLIENT"
